config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :users
  resources :funcions
  resources :peliculas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funcion.rb
class Funcion < ApplicationRecord
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  belongs_to :funcion
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  belongs_to :user
  belongs_to :funcion
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/funcions_controller.rb
class FuncionsController < ApplicationController
  before_action :set_funcion, only: [:show, :edit, :update, :destroy]

  # GET /funcions
  # GET /funcions.json
  def index
    @funcions = Funcion.all
    render json: @funcions, status: :ok 
  end

  # GET /funcions/1
  # GET /funcions/1.json
  def show
  end

  # GET /funcions/new
  def new
    @funcion = Funcion.new
  end

  # GET /funcions/1/edit
  def edit
  end

  # POST /funcions
  # POST /funcions.json
  def create
    @funcion = Funcion.new(funcion_params)

    respond_to do |format|
      if @funcion.save
        format.html { redirect_to @funcion, notice: 'Funcion was successfully created.' }
        format.json { render :show, status: :created, location: @funcion }
      else
        format.html { render :new }
        format.json { render json: @funcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcions/1
  # PATCH/PUT /funcions/1.json
  def update
    respond_to do |format|
      if @funcion.update(funcion_params)
        format.html { redirect_to @funcion, notice: 'Funcion was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcion }
      else
        format.html { render :edit }
        format.json { render json: @funcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcions/1
  # DELETE /funcions/1.json
  def destroy
    @funcion.destroy
    respond_to do |format|
      format.html { redirect_to funcions_url, notice: 'Funcion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcion
      @funcion = Funcion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcion_params
      params.require(:funcion).permit(:pelicula, :dia, :num_sillas)
    end
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_action :set_pelicula, only: [:show, :edit, :update, :destroy]

  # GET /peliculas
  # GET /peliculas.json
  def index
    @pelicula = Pelicula.all
    render json: @pelicula, status: :ok 
  end

  # GET /peliculas/1
  # GET /peliculas/1.json
  def show
    @pelicula = Pelicula.find_by(id: params[:id])
    if @pelicula
        render json: @pelicula, status: :ok
    else
        render json: {error: 'Not Found'}, status: :not_found
    end
  end

  # GET /peliculas/new
  def new
    @pelicula = Pelicula.new
  end

  # GET /peliculas/1/edit
  def edit
  end

  # POST /peliculas
  # POST /peliculas.json
  def create
    @pelicula = Pelicula.new(pelicula_params)
    respond_to do |format|
      if @pelicula.save
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully created.' }
        format.json { render :show, status: :created, location: @pelicula }
      else
        format.html { render :new }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculas/1
  # PATCH/PUT /peliculas/1.json
  def update
    @pelicula = Pelicula.find(params[:id])
    @pelicula.update(update_params)
    render json: @pelicula, status: :ok
  end

  # DELETE /peliculas/1
  # DELETE /peliculas/1.json
  def destroy
    @pelicula = Pelicula.find(params[:id])
    @pelicula.destroy
    render json: {message: 'Eliminated'}, status: :ok

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelicula
      @pelicula = Pelicula.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pelicula_params
      params.require(:pelicula).permit(:nombre, :descripcion, :url_imagen, :dia_funcion, :funcion_id)
    end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reserva_params
      params.require(:reserva).permit(:dia, :user_id, :funcion_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render json: @users, status: :ok 
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:cedula, :nombre, :correo, :celular)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcions_helper.rb
module FuncionsHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/funcions/_form.html.erb
<%= form_with(model: funcion, local: true) do |form| %>
  <% if funcion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcion.errors.count, "error") %> prohibited this funcion from being saved:</h2>

      <ul>
        <% funcion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pelicula %>
    <%= form.text_field :pelicula %>
  </div>

  <div class="field">
    <%= form.label :dia %>
    <%= form.datetime_select :dia %>
  </div>

  <div class="field">
    <%= form.label :num_sillas %>
    <%= form.number_field :num_sillas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funcions/edit.html.erb
<h1>Editing Funcion</h1>

<%= render 'form', funcion: @funcion %>

<%= link_to 'Show', @funcion %> |
<%= link_to 'Back', funcions_path %>

app/views/funcions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcions</h1>

<table>
  <thead>
    <tr>
      <th>Pelicula</th>
      <th>Dia</th>
      <th>Num sillas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcions.each do |funcion| %>
      <tr>
        <td><%= funcion.pelicula %></td>
        <td><%= funcion.dia %></td>
        <td><%= funcion.num_sillas %></td>
        <td><%= link_to 'Show', funcion %></td>
        <td><%= link_to 'Edit', edit_funcion_path(funcion) %></td>
        <td><%= link_to 'Destroy', funcion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcion', new_funcion_path %>

app/views/funcions/new.html.erb
<h1>New Funcion</h1>

<%= render 'form', funcion: @funcion %>

<%= link_to 'Back', funcions_path %>

app/views/funcions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pelicula:</strong>
  <%= @funcion.pelicula %>
</p>

<p>
  <strong>Dia:</strong>
  <%= @funcion.dia %>
</p>

<p>
  <strong>Num sillas:</strong>
  <%= @funcion.num_sillas %>
</p>

<%= link_to 'Edit', edit_funcion_path(@funcion) %> |
<%= link_to 'Back', funcions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movieshark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peliculas/_form.html.erb
<%= form_with(model: pelicula, local: true) do |form| %>
  <% if pelicula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pelicula.errors.count, "error") %> prohibited this pelicula from being saved:</h2>

      <ul>
        <% pelicula.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :url_imagen %>
    <%= form.text_field :url_imagen %>
  </div>

  <div class="field">
    <%= form.label :dia_funcion %>
    <%= form.datetime_select :dia_funcion %>
  </div>

  <div class="field">
    <%= form.label :funcion_id %>
    <%= form.text_field :funcion_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peliculas/edit.html.erb
<h1>Editing Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Show', @pelicula %> |
<%= link_to 'Back', peliculas_path %>

app/views/peliculas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peliculas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Url imagen</th>
      <th>Dia funcion</th>
      <th>Funcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= pelicula.nombre %></td>
        <td><%= pelicula.descripcion %></td>
        <td><%= pelicula.url_imagen %></td>
        <td><%= pelicula.dia_funcion %></td>
        <td><%= pelicula.funcion_id %></td>
        <td><%= link_to 'Show', pelicula %></td>
        <td><%= link_to 'Edit', edit_pelicula_path(pelicula) %></td>
        <td><%= link_to 'Destroy', pelicula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pelicula', new_pelicula_path %>

app/views/peliculas/new.html.erb
<h1>New Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Back', peliculas_path %>

app/views/peliculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pelicula.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @pelicula.descripcion %>
</p>

<p>
  <strong>Url imagen:</strong>
  <%= @pelicula.url_imagen %>
</p>

<p>
  <strong>Dia funcion:</strong>
  <%= @pelicula.dia_funcion %>
</p>

<p>
  <strong>Funcion:</strong>
  <%= @pelicula.funcion_id %>
</p>

<%= link_to 'Edit', edit_pelicula_path(@pelicula) %> |
<%= link_to 'Back', peliculas_path %>

app/views/reservas/_form.html.erb
<%= form_with(model: reserva, local: true) do |form| %>
  <% if reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
        <% reserva.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dia %>
    <%= form.datetime_select :dia %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :funcion_id %>
    <%= form.text_field :funcion_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <tr>
      <th>Dia</th>
      <th>User</th>
      <th>Funcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.dia %></td>
        <td><%= reserva.user_id %></td>
        <td><%= reserva.funcion_id %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>New Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @reserva.dia %>
</p>

<p>
  <strong>User:</strong>
  <%= @reserva.user_id %>
</p>

<p>
  <strong>Funcion:</strong>
  <%= @reserva.funcion_id %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cedula %>
    <%= form.number_field :cedula %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.cedula %></td>
        <td><%= user.nombre %></td>
        <td><%= user.correo %></td>
        <td><%= user.celular %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @user.cedula %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @user.correo %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @user.celular %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>